version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin # db user
            MONGO_INITDB_ROOT_PASSWORD: secretpassword # db password
        volumes:
            - mongo-data:/data/db

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - '8082:8081'
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin # db user
            ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword # db password
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: admin # mongo express username
            ME_CONFIG_BASICAUTH_PASSWORD: secret_me_password # mongo express login password
        depends_on:
            - mongodb

volumes:
    mongo-data:
